/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.neos.broker.gui;

import java.awt.BorderLayout;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultTreeModel;
import org.neos.broker.gui.conection.NewConnection;
import org.neos.broker.gui.conection.NewConnectionUI;
import org.neos.broker.gui.conection.NewDialogConn;
import org.neos.broker.gui.tree.DemoTree;
import org.neos.broker.gui.tree.IconNodeRenderer;
import static org.neos.broker.gui.tree.GuiUtils.createImageIcon;
import org.neos.broker.gui.tree.NodeGui;
import org.neos.broker.gui.tree.TreeMouseAdapter;

/**
 * Esta es una prueba de Mario
 * @author neossoftware
 */
public class MQApplicationJdesk extends javax.swing.JFrame {
     /*frame principal*/
      private NewDialogConn frame;

    /**
     * Creates new form MQApplicationJdesk
     */
    public MQApplicationJdesk() {
        frame = new NewDialogConn(this,true);
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
       
        //Set up the GUI.
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel4 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        ok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MQ GUI");

        splitPane.setToolTipText("");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(jTree1);
        populateValues(jTree1);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        splitPane.setLeftComponent(jPanel1);

        jPanel4.setLayout(new java.awt.BorderLayout());
        splitPane.setRightComponent(jPanel4);

        getContentPane().add(splitPane, java.awt.BorderLayout.LINE_START);

        jToolBar1.setRollover(true);

        ok.setText("ok");
        ok.setFocusable(false);
        ok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ok.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ok);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel2.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         //Make sure we have nice window decorations.
        JFrame.setDefaultLookAndFeelDecorated(true);
        /* Set the Nimbus look and feel */
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MQApplicationJdesk().setVisible(true);
            }
        });
    }
    
    public void populateValues(JTree arbol) {
        modelo =(DefaultTreeModel)arbol.getModel();
       
        NodeGui raiz = new NodeGui<>("Conexiones", true, createImageIcon("discovery.gif", "", DemoTree.class));
          
        modelo.setRoot(raiz);         
        NodeGui<String> rama = new NodeGui<>("interfaz Hogan", true,createImageIcon("plugin.gif", "", DemoTree.class) );
        
        //se crean nodos
        NodeGui<String> nodo1 = new NodeGui<>("Mensaje1",false); 
        NodeGui<String> nodo2 = new NodeGui<>("Mensaje2",false); 
        rama.add(nodo1);
        rama.add(nodo2);
        
        modelo.insertNodeInto(rama, raiz, 0);
        arbol.setCellRenderer(new IconNodeRenderer());
                 
        arbol.expandRow(0);
        arbol.addMouseListener(new TreeMouseAdapter(arbol, raiz,frame));
         
    }
    
    private DefaultTreeModel modelo;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton ok;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
